name: Fetch EDEKA Offers

on:
  schedule:
    - cron: "0 21 * * 0" # Runs every Sunday at 9 PM UTC (11 PM Berlin time)
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  fetch-and-store:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "24591225+bmmmm@users.noreply.github.com"

      - name: Fetch data from EDEKA API
        id: fetch-data
        run: |
          API_URL="https://www.edeka.de/api/auth-proxy/?path=api%2Foffers%3Flimit%3D999%26marketId%3D5625811"
          RESPONSE=$(curl -s "$API_URL")
          echo "$RESPONSE" > data.json
          
      - name: Sort JSON by category
        run: |
          RAW_JSON=$(cat data.json)
          SORTED_JSON=$(echo "$RAW_JSON" | jq '.
            offers |= sort_by(.category.name)
          ')
          echo "$SORTED_JSON" > data.json

      - name: Determine folder and file structure
        id: structure
        run: |
          CURRENT_DATE=$(date -u +"%Y-%m-%d")
          YEAR=$(date -u +"%Y")
          WEEK="KW$(date -u +"%V")"
          FOLDER="data/$YEAR/$WEEK"
          FILE="$CURRENT_DATE.json"
          mkdir -p "$FOLDER" # Create the full folder structure
          mv data.json "$FOLDER/$FILE"
          echo "folder=$FOLDER" >> $GITHUB_OUTPUT
          echo "file=$FOLDER/$FILE" >> $GITHUB_OUTPUT

      - name: Generate folder-structure.json
        id: generate-structure
        run: |
          # Find all JSON files in the data directory and generate folder-structure.json
          find data -type f -name "*.json" | sort | jq -R -s -c 'split("\n") | map(select(length > 0))' > data/folder-structure.json

      - name: Commit and push data
        run: |
          git add data/
          git commit -m "Add data for ${{ steps.structure.outputs.file }} and update folder structure"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.ABUFS_AJUN13_TOKEN }}
          FOLDER: ${{ steps.structure.outputs.folder }}
          FILE: ${{ steps.structure.outputs.file }}